(print  "welcome to CLISP online ide from JDoodle.com")
(print "Bienvenido a la tabla de tipos de pokémon")
(print "Cuántos tipos tiene su pokemon?")
(print "1")
(print "2")

(print "input usuario 2")
(print "Cuál es el primer tipo?")
(print "1 Agua")
(print "2 Planta")
(print "3 Fuego")
(print "4 Acero")
(print "5 Volador")
(print "6 texto aqui")
(print "7")
(print "8")
(print "9")
(print "10")

(print "Input usuario: 1")
(print "CUàl es el segundo tipo?")
(print "1 Agua")
(print "2 Planta")
(print "3 Fuego")
(print "4 Acero")
(print "5 Volador")
(print "6 texto aqui")
(print "7")
(print "8")
(print "9")
(print "10")

(print "input usuario 5")
(print "Su pokemon es debil contra:")
(print "Electrico")
(print "Roca")
